### PR TITLE
[DOCS] add readme file

### LINKED ISSUE #7: [DOCS] add readme file
### Description

`Readme.md` file is needed to describe the project and give instructions and how to contribute, including the technologies used

use [this](https://github.com/Dun-sin/anon-chat-app) as a guide

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by SRADHA-SURESH12**
## 🛠️ Fixes Issue

 Closes #7  

## 👨‍💻 Changes proposed(required)

- Added separate sections for getting started, prerequisites
- Added logo of smart search on the readme.
- Restructured the readme file for better understanding.

## ✔️ Check List (Check all the applicable boxes)(required) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

Some more modifications are possible.

### CODE REVIEW

**Comment by Dun-sin** [comment]
There's a pull request template, pls use it, thank you

**Comment by SRADHA-SURESH12** [comment]
Can you tell me where can I find it?

**Comment by Dun-sin** [comment]
> Can you tell me where can I find it?

You saw some demo text while you were creating this pull request, right?
That's a template

**Comment by SRADHA-SURESH12** [comment]
Ohh that one! Okay sorry from my end I will update and make a new PR.

**Comment by SRADHA-SURESH12** [comment]
[DOCS] add readme file #7 

## 🛠️ Fixes Issue

 Closes #7  

## 👨‍💻 Changes proposed(required)

- Added separate sections for getting started, prerequisites
- Added logo of smart search on the readme.
- Restructured the readme file for better understanding.

## ✔️ Check List (Check all the applicable boxes)(required) 




- [ x] My code follows the code style of this project.
- [ x] This PR does not contain plagiarized content.
- [ x] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

Some more modifications are possible.

**Comment by Dun-sin** [comment]
> [DOCS] add readme file #7
> ## 🛠️ Fixes Issue
> 
> Closes #7
> ## 👨‍💻 Changes proposed(required)
> 
>     * Added separate sections for getting started, prerequisites
> 
>     * Added logo of smart search on the readme.
> 
>     * Restructured the readme file for better understanding.
> 
> 
> ## ✔️ Check List (Check all the applicable boxes)(required)
> 
>     * [ x] My code follows the code style of this project.
> 
>     * [ x] This PR does not contain plagiarized content.
> 
>     * [ x] The title of my pull request is a short description of the requested changes.
> 
> 
> ## 📄 Note to reviewers
> 
> Some more modifications are possible.

don't do this, you can edit the orignal message

**Comment by SRADHA-SURESH12** [comment]
Sorry again ! Updated my orginal comment please check it. Thank you :)

**Review by Dun-sin — APPROVED** [review]
Looks good to merge, thanks for this

**Comment by SRADHA-SURESH12** [comment]
Thank you Dunsin for being patient with the changes ! Have a nice day :)

**Comment by Dun-sin** [comment]
> Thank you Dunsin for being patient with the changes ! Have a nice day :)

Yeah! You are welcome, tho you kind of scattered a lot of things 😭 which I have to now fix 😅
but yeah when contributing to a readme, try to look at what you have done in the preview section so you know what to fix and make look better

**Pull request merged**
