### PR TITLE
Add feature review

### PR DESCRIPTION
**Pull request by unkwnownGriot**
## ✔️ Check List (Check all the applicable boxes)(required) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots
2022-09-16 11_30_32-Window

### CODE REVIEW

**Comment by Dun-sin** [comment]
thanks for this but you filled PR wrong, read the header for clues

**Comment by unkwnownGriot** [comment]
hi dunsin how are you? I don't understand well what i should do i'm new to open source on github and this is my first contribution can you help me to figure out what i'm doing wrong?

**Comment by Dun-sin** [comment]
Check this out

https://github.com/Dun-sin/smartsearch/pull/20

**Comment by unkwnownGriot** [comment]
thank you it's more clear now

**Pull request closed without merging**
