### PR TITLE
fix: Mobile details page looking off

### LINKED ISSUE #11: [BUG] The detailed page looks off in Mobiles
### Description

 - The Image looks streched more than it should have been. ( Take a look at `Image 1`)
 - The texts are also too close to each other and provides an overall bad UI/UX for the mobile view

### Fixes ? 

- i would like to make the picture in a much more `contain` manner.
- Also some increased margin/padding for the texts !

## Image 1

image

### PR DESCRIPTION
**Pull request by rachzy**
## 👨‍💻 Changes proposed(required)

* add a margin distance between "details" divs in Phone page, like seen in `Screenshot_1`
* fix stretched image and adjust its resolution to make it more "contained" (`Screenshot_1`)

## ✔️ Check List (Check all the applicable boxes)(required) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### Before
Before
### After
Screenshot_1

### CODE REVIEW

**Comment by Dun-sin** [comment]
No one asked you to work on this.

Will be closed

**Comment by rachzy** [comment]
public and open issue, no one assigned, "good first issue" label
just tried to help

**Comment by Dun-sin** [comment]
> public and open issue, no one assigned, "good first issue" label just tried to help

Great, thanks for the thoughts. But someone was already wanting to work on this.

Never create a pull request for an issue no one gave you the permission to work on because someone may already be working on it💪🏽

**Comment by rachzy** [comment]
Kay! Thanks for the tip =D

**Pull request closed without merging**
