### PR TITLE
Added Contributing guidelines

### PR DESCRIPTION
**Pull request by hasnainmakada-99**
## 👨‍💻 Changes proposed(required)
- Added contribution guidelines for contributors
- And also linked the contribution file in `readme.md`

## ✔️ Check List (Check all the applicable boxes)(required) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by Dun-sin** [comment]
Check [this](https://github.com/Dun-sin/smartsearch/pull/6) on how to fill a pull request template

**Comment by hasnainmakada-99** [comment]
> Check [this](https://github.com/Dun-sin/smartsearch/pull/6) on how to fill a pull request template

Sure @Dun-sin

**Comment by hasnainmakada-99** [comment]
@Dun-sin  this link is redirecting me towards some issue but not a guide on how to fill a pull request template

**Comment by Dun-sin** [comment]
> @Dun-sin this link is redirecting me towards some issue but not a guide on how to fill a pull request template

Well when you were filing the pull request, there were some instructions you didn't follow. The link takes you to what you should have done, if you didn't delete the comments in the pull request template.

Trying reading it again

**Comment by hasnainmakada-99** [comment]
> 

Ohh ya now I got it, I didn't fill the checkboxes as it was mentioned on the top headline, Sorry

**Comment by hasnainmakada-99** [comment]
> > 
> 
> Ohh ya now I got it, I didn't fill the checkboxes as it was mentioned on the top headline, Sorry

So, Now what I have to do is just check all the checkboxes right @Dun-sin ?

**Comment by hasnainmakada-99** [comment]
> > > 
> > 
> > 
> > Ohh ya now I got it, I didn't fill the checkboxes as it was mentioned on the top headline, Sorry
> 
> So, Now what I have to do is just check all the checkboxes right @Dun-sin ?

As well as tell the changes proposed

**Comment by Dun-sin** [comment]
> > 
> 
> Ohh ya now I got it, I didn't fill the checkboxes as it was mentioned on the top headline, Sorry

Also the changes proposed part, just letting you know for next time

**Pull request merged**
